// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use direct_implementation::methods::{GUEST_CSL_ELF, GUEST_CSL_ID};

use risc0_zkvm::{default_prover, serde::from_slice, ExecutorEnv};
use std::time::Instant;

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    env_logger::init();

    let now = Instant::now();

    println!("Setting up env...");

    let env = ExecutorEnv::builder().build().unwrap();

    // Next, we make a prover.
    let prover = default_prover();

    println!("Checking the proof and generating the receipt...");

    // Run the prover on the ELF binary to produce a receipt.
    let receipt = prover.prove_elf(env, GUEST_CSL_ELF).unwrap();

    let provetime = now.elapsed().as_millis();

    println!("Proved in {} ms", provetime);

    receipt.verify(GUEST_CSL_ID).unwrap();

    println!("Verified in {} ms", now.elapsed().as_millis() - provetime);

    // Get the host's size of a usize pointer
    let size_of_usize = std::mem::size_of::<usize>();

    // Small fetcher that returns the next chunk of given size from journal
    let current_index: usize = receipt.journal.bytes.len() - size_of_usize;
    let next_journal_chunk = |size: usize| -> &[u8] {
        let ret = &receipt.journal.bytes[current_index..current_index + size];
        return ret;
    };

    // Get the result of the execution
    let _ret: usize = from_slice(next_journal_chunk(size_of_usize)).unwrap();

    let total_cycles: usize = from_slice(next_journal_chunk(size_of_usize)).unwrap();
    println!("Total cycles {}", total_cycles);

    println!(
        "Running execution + ZK certficate generation + verification took {} ms",
        now.elapsed().as_millis()
    );
}
